<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.0.9</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ApprovalTests" Version="7.0.0" />
      <PackageReference Include="itext" Version="9.3.0" />
    </ItemGroup>

</Project>
